- name: PLAY-1
  hosts: localhost
  tasks: 
    - name: PLAY-1 and TASK-1
      ansible.builtin.debug:
        "msg": "Hi, Iam from PLAY-1 and TASK-1"

    - name: PLAY-1 and TASK-2
      ansible.builtin.debug:
        "msg": "Hi, Iam from PLAY-1 and TASK-2"