- name: variables
  hosts: localhost
  vars:
    COURSE: "Devops"
    TRAINER: "RADHAKRISHNA"
    DURATION: "120hrs"
  tasks:
    - name: printing variables
      ansible.builtin.debug:
       "msg": "Hi, we are learning {{COURSE}} from Trainer {{TRAINER}}, Duration is {{DURATION}}"
    