- name: vars_tasks
  hosts: web
  vars:
    COURSE: "Ansible"
    TRAINER: "RADHAKRISHNA"
    DURATION: "15hrs"
  tasks:
    - name: variable TASK-1
      vars: 
        COURSE: "TASK-1"
      ansible.builtin.debug:
        "msg": "Hi, we are learing {{COURSE}} from {{TRAINER}}, Duration is {{DURATION}}"
    
    - name: variable TASK-2
      ansible.builtin.debug:
        "msg": "Hi, we are learning {{COURSE}} from {{TRAINER}}, Duration is {{Duration}}
