- name: variables from files
  hosts: web
  vars_files:
    - variables.yaml
  tasks: 
    - name: variables call from file
    ansible.builtin.debug:
      "msg": "Hi, i'm learning {{COURSE}} from trainer {{TRAINER}}, Duration is {{DURATION}}"
