- name: items2dist
  hosts: localhost
  vars:
    my_list:
      - {'key': 'course', 'value': 'ansible'}
      - {'key': 'trainer', 'value': 'Radhakrishna'}
      - {'key': 'duration', 'value': '120hrs'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert is: {{my_list}}"

  - name: after convert
    ansible.builtin.debug:
      msg: "after convert is: {{my_list | items2dict}}"