- name: print default
  hosts: localhost
  tasks:
  - name: print default
    ansible.builtin.debug:
      msg: "Default print is : {{course | default('Ansible')}}"
---

- name: upper case
  hosts: localhost
  vars:
    course: "hello guru"
  tasks: 
  - name: uppercase
    ansible.builtin.debug:
      msg: "print upper case of hello guru is {{course | upper}}"