- name: print min and max
  hosts: localhost
  vars:
    ages: [25, 53, 58, 78, 100]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age is: {{ages | min}}, max age is: {{ages | max}}"
