- name: install, service and enable nginx
  hosts: localhost
  become: yes
  tasks: 
    - name: install nginx
      ansible.builtin.dnf:
        state: latest

    - name: service 
      ansible.builtin.service:
        state: started
        enabled: yes


