- name: vars_prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: please enter username
      private: false

    - name: PASSWORD
      prompt: please enter password
      private: true

  tasks:
    - name: vars_prompt
      ansible.builtin.debug:
        msg: "username is {{USERNAME}}, password is {{PASSWORD}}"