- name: mysql
  hosts: db
  vars:
    local_host: db.jeeta.online
  become: yes

  vars_prompt: setup root password
  - name: mysql_root_password
    prompt: please enter mysql root password
    private: no

  
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install python sql dependencies
      ansible.builtin.pip:
        name:
        - PyMySQL
        - cryptography
        executable: pip3.9

    # check password is already setup or not
    - name: check db connection
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{mysql_root_password}}"
        login_host: "{{local_host}}"
        filter: version
      ignore_errors: yes
      register: mysql_connection_output

    - name: print output of db connection
      ansible.builtin.debug:
        msg: "output: {{mysql_connection_output}}"

    - name: setup root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
      when: mysql_connection_output.failed is true



  